### ISSUE TITLE
Warning: Error in : object 'nn' not found

### ISSUE THREAD

**Issue by ceefluz** [amcrisan/Adjutant#11]
Great tool, but currently I'm running into some problems. 

Running the shiny app and initiating topic clustering results in a crash with the warning: `Warning: Error in : object 'nn' not found` 

Reproducing the analysis bypassing the shiny app produces the same error. I think it originates from `tidyCorpus` function line 24 (`dplyr::count()`). The same errors also occurs in `getTopTerms` probably from line 7-8 `dplyr::count() %>% 
        ungroup() %>% arrange(-nn)`

**Comment by amcrisan** [comment]
I am currently digging into this. Its a new error that's popped up in the past couple of weeks. Its not one that I can reproduce on my end so I am looking to whether packages or different environments are the source of the problem.

**Comment by ceefluz** [comment]
Solved for `dplyr` version 0.7.8 but unfortunately error still occurs with version 0.8.0.1

**Comment by clynne** [comment]
> Solved for `dplyr` version 0.7.8 but unfortunately error still occurs with version 0.8.0.1

I'm having the same issue with dplyr version 0.8.0.1, screen shot below:
![image](https://user-images.githubusercontent.com/49412502/56144635-be962e80-5f70-11e9-9022-3dec7fc86c36.png)
