### ISSUE TITLE
optClusters

### ISSUE THREAD

**Issue by marco-scalvini** [amcrisan/Adjutant#6]
Hi
I am trying to use Adjutant within my own code, bypassing the Shiny application, I followed the script you included but  when I run the appHDBSCAN to select the optimal cluster parameters automatically I get the following error:

optClusters <- optimalParam(df)

Error in data.frame(PMID = as.character(corpus$PMID), cluster = cl$cluster,  : 
  arguments imply differing number of rows: 1102, 0

the DF has 1102 rows.

**Comment by amcrisan** [comment]
@marco-scalvini : can you send post your search string? Haven't been able to reproduce error on my own.

**Comment by amcrisan** [comment]
No response and was not able to reproduce the issue
