### ISSUE TITLE
Doesn't work today

### ISSUE THREAD

**Issue by Huimincheng2015** [amcrisan/Adjutant#7]
Hi, I run the same following code today,  it doesn't work now, however, it did work weeks ago.
This is my code:
processSearch("epilepsy")

And this is what I get:
![image](https://user-images.githubusercontent.com/16879905/49611985-4cce2880-f971-11e8-9f3d-0acfce923570.png)

 Weeks ago, I ran the same code successfully. But today I failed. I don't know what happened. Can you help me with that?

**Comment by amcrisan** [comment]
hmmm, I suspect that what is happening is that the NCBI server might be kicking you off your connection. I have seen this error happen before too and I re-run the query later and it works.  I did include some time delays into Adjutant so that this doesn't happen to often, but when I get a little more time I will try to address it a little bit more robustly.

**Comment by Huimincheng2015** [comment]
Ohhh that makes sense, connection is not always allowed, got it!  I will try it later, many thanks : D

**Comment by amcrisan** [comment]
Let me know if the problem continues to exist. It may also help to limit you query to a just 20,000 or 30,000 articles. Since Adjutant is a stand alone app, really massive queries will be downloaded very slowly over the internet from NCBI to your computer, which has an impact on your connection.

**Comment by Huimincheng2015** [comment]
Thank you! I add an argument "retmax=2000", and it still shows the same error. I think my problem is the prohibited connection, not the massive queries.  Anyway, I  will try it later.

**Comment by Huimincheng2015** [comment]
I am sorry to say it still doesn't work......still the same error

**Comment by amcrisan** [comment]
Ok - I tried to add something that might help with your connection issues. Whenever the Adjutant cannot initially get an abstract, it tries a different route to get it. So what I've written is a way for you to get around that, which speeds up the analysis a little, but you will have to maybe filter out a couple of articles that don't get abstracts.

try:
processSearch("epilepsy", forceGet = FALSE)
