### ISSUE TITLE
Adjutant download and install problem

### ISSUE THREAD

**Issue by XichenEthanZhang** [amcrisan/Adjutant#8]
It is a fascinating tool. I am highly interested but I know nothing about R. Today I tried to follow the instruction to install but failed. Please see the error msg below. Hope someone can help me out. Thank you.
![snipimage](https://user-images.githubusercontent.com/46685514/51129209-25992f80-182a-11e9-9e9f-0b9b5f40d24e.JPG)

**Comment by amcrisan** [comment]
Hi! Your situation is interesting because you might be the freshest install of R and adjutant to date!

When there is an error like the one you recieved "there is no packaged called 'magrittr' ", the solution is to install the package manually as follows:

install.packages('magrittr')

Now - what I've been looking into is why it did not install automatically when you downloaded Adjutant (this is the first time I've seen this error message). I am still working on figuring this out. Adjutant does no specifically use the magrittr package, so I am still looking into a better solution to this kind of problem. 

For now, please install the missing package manually. If there are more packages that do no install, please let me know, so that I can dig into this problem more.

**Comment by XichenEthanZhang** [comment]
Hi there. Thanks for your reply. I tried to manually install 'magrittr' and relaunched the adjutant install. Then another missing package 'backports' popped out. I did manually install 'backports' and tried adjutant install again. More errors occurred as follows:
Error: (converted from warning) cannot remove prior installation of package ‘backports’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers


The full script are shown below for your reference. Look forward to your kind assistance. Thanks a lot.

> devtools::install_github("amcrisan/Adjutant")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’
> install.packages('backports')
Installing package into ‘U:/Data/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/backports_1.1.3.zip'
Content type 'application/zip' length 66110 bytes (64 KB)
downloaded 64 KB

package ‘backports’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xz720938\AppData\Local\Temp\Rtmpm61QGG\downloaded_packages
> devtools::install_github("amcrisan/Adjutant")
Downloading GitHub repo amcrisan/Adjutant@master
Installing 70 packages: assertthat, backports, BH, bindr, bindrcpp, broom, cli, colorspace, crayon, crosstalk, dbscan, digest, dplyr, DT, fansi, generics, ggplot2, ggthemes, glue, gtable, htmltools, htmlwidgets, httpuv, hunspell, ISOcodes, janeaustenr, jsonlite, labeling, later, lazyeval, magrittr, mime, munsell, NLP, pillar, pkgconfig, plogr, plyr, promises, purrr, R6, RColorBrewer, Rcpp, reshape2, RISmed, rlang, Rtsne, scales, shiny, shinydashboard, shinyWidgets, slam, SnowballC, sourcetools, stopwords, stringi, stringr, tibble, tidyr, tidyselect, tidytext, tm, tokenizers, utf8, viridisLite, withr, wordcloud, xml2, xtable, yaml
Installing packages into ‘U:/Data/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/assertthat_0.2.0.zip'
Content type 'application/zip' length 43936 bytes (42 KB)
downloaded 42 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/backports_1.1.3.zip'
Content type 'application/zip' length 66110 bytes (64 KB)
downloaded 64 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/BH_1.69.0-1.zip'
Content type 'application/zip' length 19008162 bytes (18.1 MB)
downloaded 18.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bindr_0.1.1.zip'
Content type 'application/zip' length 15280 bytes (14 KB)
downloaded 14 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bindrcpp_0.2.2.zip'
Content type 'application/zip' length 622180 bytes (607 KB)
downloaded 607 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/broom_0.5.1.zip'
Content type 'application/zip' length 1865254 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/cli_1.0.1.zip'
Content type 'application/zip' length 560713 bytes (547 KB)
downloaded 547 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/colorspace_1.4-0.zip'
Content type 'application/zip' length 2361625 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/crayon_1.3.4.zip'
Content type 'application/zip' length 710488 bytes (693 KB)
downloaded 693 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/crosstalk_1.0.0.zip'
Content type 'application/zip' length 600712 bytes (586 KB)
downloaded 586 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/dbscan_1.1-3.zip'
Content type 'application/zip' length 2658881 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/digest_0.6.18.zip'
Content type 'application/zip' length 176447 bytes (172 KB)
downloaded 172 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/dplyr_0.7.8.zip'
Content type 'application/zip' length 2859440 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/DT_0.5.zip'
Content type 'application/zip' length 946896 bytes (924 KB)
downloaded 924 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/fansi_0.4.0.zip'
Content type 'application/zip' length 187015 bytes (182 KB)
downloaded 182 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/generics_0.0.2.zip'
Content type 'application/zip' length 54487 bytes (53 KB)
downloaded 53 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/ggplot2_3.1.0.zip'
Content type 'application/zip' length 3177649 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/ggthemes_4.0.1.zip'
Content type 'application/zip' length 347794 bytes (339 KB)
downloaded 339 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/glue_1.3.0.zip'
Content type 'application/zip' length 108180 bytes (105 KB)
downloaded 105 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gtable_0.2.0.zip'
Content type 'application/zip' length 58269 bytes (56 KB)
downloaded 56 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/htmltools_0.3.6.zip'
Content type 'application/zip' length 617864 bytes (603 KB)
downloaded 603 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/htmlwidgets_1.3.zip'
Content type 'application/zip' length 774095 bytes (755 KB)
downloaded 755 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/httpuv_1.4.5.1.zip'
Content type 'application/zip' length 1133502 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/hunspell_3.0.zip'
Content type 'application/zip' length 1835389 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/ISOcodes_2018.06.29.zip'
Content type 'application/zip' length 303747 bytes (296 KB)
downloaded 296 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/janeaustenr_0.1.5.zip'
Content type 'application/zip' length 1624435 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jsonlite_1.6.zip'
Content type 'application/zip' length 1116705 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/labeling_0.3.zip'
Content type 'application/zip' length 41179 bytes (40 KB)
downloaded 40 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/later_0.7.5.zip'
Content type 'application/zip' length 617545 bytes (603 KB)
downloaded 603 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lazyeval_0.2.1.zip'
Content type 'application/zip' length 140187 bytes (136 KB)
downloaded 136 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/magrittr_1.5.zip'
Content type 'application/zip' length 155906 bytes (152 KB)
downloaded 152 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mime_0.6.zip'
Content type 'application/zip' length 38886 bytes (37 KB)
downloaded 37 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/munsell_0.5.0.zip'
Content type 'application/zip' length 220580 bytes (215 KB)
downloaded 215 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/NLP_0.2-0.zip'
Content type 'application/zip' length 300976 bytes (293 KB)
downloaded 293 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pillar_1.3.1.zip'
Content type 'application/zip' length 88842 bytes (86 KB)
downloaded 86 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pkgconfig_2.0.2.zip'
Content type 'application/zip' length 20094 bytes (19 KB)
downloaded 19 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/plogr_0.2.0.zip'
Content type 'application/zip' length 18737 bytes (18 KB)
downloaded 18 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/plyr_1.8.4.zip'
Content type 'application/zip' length 1219407 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/promises_1.0.1.zip'
Content type 'application/zip' length 648537 bytes (633 KB)
downloaded 633 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/purrr_0.2.5.zip'
Content type 'application/zip' length 243743 bytes (238 KB)
downloaded 238 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/R6_2.3.0.zip'
Content type 'application/zip' length 36674 bytes (35 KB)
downloaded 35 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RColorBrewer_1.1-2.zip'
Content type 'application/zip' length 26965 bytes (26 KB)
downloaded 26 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_1.0.0.zip'
Content type 'application/zip' length 4347081 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/reshape2_1.4.3.zip'
Content type 'application/zip' length 611638 bytes (597 KB)
downloaded 597 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RISmed_2.1.7.zip'
Content type 'application/zip' length 327312 bytes (319 KB)
downloaded 319 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rlang_0.3.1.zip'
Content type 'application/zip' length 1078525 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rtsne_0.15.zip'
Content type 'application/zip' length 691372 bytes (675 KB)
downloaded 675 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/scales_1.0.0.zip'
Content type 'application/zip' length 939994 bytes (917 KB)
downloaded 917 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/shiny_1.2.0.zip'
Content type 'application/zip' length 3540846 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/shinydashboard_0.7.1.zip'
Content type 'application/zip' length 307037 bytes (299 KB)
downloaded 299 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/shinyWidgets_0.4.4.zip'
Content type 'application/zip' length 1665321 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/slam_0.1-44.zip'
Content type 'application/zip' length 121869 bytes (119 KB)
downloaded 119 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/SnowballC_0.6.0.zip'
Content type 'application/zip' length 3082568 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/sourcetools_0.1.7.zip'
Content type 'application/zip' length 528205 bytes (515 KB)
downloaded 515 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stopwords_0.9.0.zip'
Content type 'application/zip' length 135455 bytes (132 KB)
downloaded 132 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.2.4.zip'
Content type 'application/zip' length 15191905 bytes (14.5 MB)
downloaded 14.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringr_1.3.1.zip'
Content type 'application/zip' length 171572 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tibble_2.0.1.zip'
Content type 'application/zip' length 644361 bytes (629 KB)
downloaded 629 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tidyr_0.8.2.zip'
Content type 'application/zip' length 903329 bytes (882 KB)
downloaded 882 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tidyselect_0.2.5.zip'
Content type 'application/zip' length 624992 bytes (610 KB)
downloaded 610 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tidytext_0.2.0.zip'
Content type 'application/zip' length 2810266 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tm_0.7-6.zip'
Content type 'application/zip' length 1276415 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tokenizers_0.2.1.zip'
Content type 'application/zip' length 1138620 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/utf8_1.1.4.zip'
Content type 'application/zip' length 194678 bytes (190 KB)
downloaded 190 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/viridisLite_0.3.0.zip'
Content type 'application/zip' length 57077 bytes (55 KB)
downloaded 55 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_2.1.2.zip'
Content type 'application/zip' length 123746 bytes (120 KB)
downloaded 120 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/wordcloud_2.6.zip'
Content type 'application/zip' length 580056 bytes (566 KB)
downloaded 566 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/xml2_1.2.0.zip'
Content type 'application/zip' length 3534434 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/xtable_1.8-3.zip'
Content type 'application/zip' length 701231 bytes (684 KB)
downloaded 684 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/yaml_2.2.0.zip'
Content type 'application/zip' length 200366 bytes (195 KB)
downloaded 195 KB

package ‘assertthat’ successfully unpacked and MD5 sums checked
package ‘backports’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘backports’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by amcrisan** [comment]
whoa! That's a lot message. Your install situation is definitely very unique. What operating system are you running?

**Comment by XichenEthanZhang** [comment]
I am running windows 7 pro and my Rstudio is 1.1.423.

**Comment by amcrisan** [comment]
Ok - there are a few sources of error that I considered and a couple potential solutions. Please note:  I am assuming that you don't use R at all.  The recommendations below ask you to update R and several packages, which may effect any existing R code you've written. 

**1) Try using the 'remotes' instead of 'devtools' to install the package.** This is how you do that:

install.packages("remotes")
remotes::install_github("amcrisan/adjutant")

When it prompts you to update or install packages look for the option (close to the end that says 'All') for me, this was option 42, it might be different for you because you have such a new install.

I noticed that devtools sometimes causes the error you're seeing and some people saw that the remotes package helped to address this issue.


**2) If that doesn't work, try to update R (not RStudio).** I noticed that you are using R version 3.4.3 - some people indicated particular issues with this verison of R and some packages. The current version of R is 3.5. You can download the latest version of R.

Since you are using windows, you can actually use a pakcage called 'installr' to update R (here's how to do that : https://www.r-statistics.com/2013/03/updating-r-from-r-on-windows-using-the-installr-package/)

You can also download R from the official R website: https://cloud.r-project.org/

**3) The final possibility is there are some libraries on your computer that are missing.** This is different than R packages, it could be that gcc libraries are missing. If you were on a MAC I would also recommend you consider updating your command line tools, but windows does not have such a thing. So, if option 1 and 2 don't work, then I'll have to think a better option three.

Try these and let me know how it works! Thanks for continuing to trying the install.

**Comment by XichenEthanZhang** [comment]
Thanks a lot for always coming back to my naive request promptly. 
I updated my R to 3.52 and tried remote install and devtools install, but both ended up with errors. Maybe you have a better idea. Appreciate your patient explanation.

REMOTE 
> install.packages("remotes")
Installing package into ‘U:/Data/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependencies ‘methods’, ‘utils’ are not available
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/remotes_2.0.2.zip'
Content type 'application/zip' length 273128 bytes (266 KB)
downloaded 266 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xz720938\AppData\Local\Temp\RtmpQfMqJZ\downloaded_packages
> remotes::install_github("amcrisan/adjutant")
Downloading GitHub repo amcrisan/adjutant@master
Skipping 9 packages not available: graphics, grDevices, grid, methods, parallel, stats, tcltk, tools, utils
Installing 84 packages: assertthat, backports, BH, bindr, bindrcpp, broom, cli, colorspace, crayon, crosstalk, dbscan, digest, dplyr, DT, fansi, generics, ggplot2, ggthemes, glue, graphics, grDevices, grid, gtable, htmltools, htmlwidgets, httpuv, hunspell, ISOcodes, janeaustenr, jsonlite, labeling, later, lattice, lazyeval, magrittr, MASS, Matrix, methods, mgcv, mime, munsell, nlme, NLP, parallel, pillar, pkgconfig, plogr, plyr, promises, purrr, R6, RColorBrewer, Rcpp, reshape2, RISmed, rlang, Rtsne, scales, shiny, shinydashboard, shinyWidgets, slam, SnowballC, sourcetools, stats, stopwords, stringi, stringr, tcltk, tibble, tidyr, tidyselect, tidytext, tm, tokenizers, tools, utf8, utils, viridisLite, withr, wordcloud, xml2, xtable, yaml
Installing packages into ‘U:/Data/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) packages ‘graphics’, ‘grDevices’, ‘grid’, ‘methods’, ‘parallel’, ‘stats’, ‘tcltk’, ‘tools’, ‘utils’ are not available (for R version 3.5.2)
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

------------------------------------------------------------------------------------------------------------------
DEVTOOLS
> devtools::install_github("amcrisan/Adjutant")
Downloading GitHub repo amcrisan/Adjutant@master
Skipping 9 packages not available: graphics, grDevices, grid, methods, parallel, stats, tcltk, tools, utils
Installing 84 packages: assertthat, backports, BH, bindr, bindrcpp, broom, cli, colorspace, crayon, crosstalk, dbscan, digest, dplyr, DT, fansi, generics, ggplot2, ggthemes, glue, graphics, grDevices, grid, gtable, htmltools, htmlwidgets, httpuv, hunspell, ISOcodes, janeaustenr, jsonlite, labeling, later, lattice, lazyeval, magrittr, MASS, Matrix, methods, mgcv, mime, munsell, nlme, NLP, parallel, pillar, pkgconfig, plogr, plyr, promises, purrr, R6, RColorBrewer, Rcpp, reshape2, RISmed, rlang, Rtsne, scales, shiny, shinydashboard, shinyWidgets, slam, SnowballC, sourcetools, stats, stopwords, stringi, stringr, tcltk, tibble, tidyr, tidyselect, tidytext, tm, tokenizers, tools, utf8, utils, viridisLite, withr, wordcloud, xml2, xtable, yaml
Installing packages into ‘U:/Data/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) packages ‘graphics’, ‘grDevices’, ‘grid’, ‘methods’, ‘parallel’, ‘stats’, ‘tcltk’, ‘tools’, ‘utils’ are not available (for R version 3.5.2)
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by amcrisan** [comment]
Thank you for being patient as I try sort out these installation challenges.

It seems that there are still a number of dependencies that are not correctly downloading. True for both adjutant, and it seems like the remotes package too. 

Here is one thing I think you can try to get those dependencies installed on your computer, while I continue to try sort this out.

install.packages("tidyverse", dependencies = TRUE)

This should install a number of packages that adjutant needs, but seems to not be properly downloading. Then, it could help with installing adjutant.

Thanks for you patience as I try sort out what's going on. Your feedback is helping me to understand how I can improve adjutant for others.
